---
datacenter:
  childrens:
    routers:
      hostes:
        10.172.16.1[1:3]
      vars:
        testVar:999

  vars:
    ansible_connection=network_cli
    ansible_network_os=ios
    ansible_user=admin
    ansible_ssh_pass=admin